### ISSUE TITLE
Parameter sweep with initial value

### ISSUE THREAD

**Issue by feschmidt** [qucat/qucat#13]
When a circuit element is labelled **and** has a value, it is not possible to do parameter sweeps. Instead qucat returns `ValueError: L_J is not the label of a circuit element`, which can be inconvenient because it would require you to rewrite the circuit, instead of just reusing it

- OS: Ubuntu 18.04.2 LTS
- Example file: [felix_test3.txt](https://github.com/mgely/qucat/files/3165648/felix_test3.txt)

**Comment by gsteele13** [comment]
I think this is addressed: 

https://github.com/qucat/qucat/issues/83
