### ISSUE TITLE
Add code formatting with Black

### ISSUE THREAD

**Issue by DanielSank** [qucat/qucat#54]
[Black](https://black.readthedocs.io/en/stable/) is a good Python formatter. It would automatically format the existing code and can be used to check for format errors on new pull requests.

**Comment by mgely** [comment]
Great idea.
On it!

**Comment by mgely** [comment]
Adressed in 4671b03e5d40ea02bbd78cb4aab1436928ce3d50
Details have been added to the online documentation. As this is not online yet (these changes have only been pushed to the dev branch) here is a summary:
![image](https://user-images.githubusercontent.com/10977359/68217142-62652b80-ffe2-11e9-96e5-a631ed1f9c77.png)

**Comment by mgely** [comment]
Update:
At the moment the automatic formatting check that can be performed with Travis is very much dependent on the version of Black which is used by Travis and by the developper.

For example, Travis installed by default an earlier version "black-19.3b0" whereas the version on my computer is "black-19.10b0": this causes the build to fail on Travis. 

I'm afraid that if a developer has to spend a lot of time trying to get the build to pass on Travis for such a reason, it will hurt his morale.

-> Since even these two close versions have different formatting definitions which can lead to builds failing, I chose to make the use of Black a recommendation rather than a hard requirement (I removed the check in Travis) 

We can reverse this at a later stage, for example when Black exits beta stage.

**Comment by DanielSank** [comment]
Why not just pin the version of Black in a pip `requirements.txt` file?

**Comment by DanielSank** [comment]
A common way to deal with this is to add a `requirements.txt` file to the repo. When a developer clones the repo, they then do something like
```
mkvirtualenv qucat-dev
pip install -r requirements.txt
```
which installs all development requirements (including Black) into their virtual environment.

**Comment by mgely** [comment]
We could also do that, I actually created requirements-dev.txt for this purpose.
But we have to trust that a potential contributor will install black by calling
``pip install -r requirements-dev.txt`` 
and not run ``pip-install black``.
And if he dosn't create an environment for the project and then runs ``conda update --all`` all of a sudden the build could fail. 
It's tricky.. I don't know if people will actually do things properly and create an environment for the project or if it will cause problems.. what would you do?

**Comment by DanielSank** [comment]
By the way, regarding morale: I think having properly formatted code will attract developers, and those developers probably won't be scared off by having to use a virtualenv. When I saw the unformatted docstrings in `core.py` I did have a moment of doubt about contributing to the project. I think proper code formatting is a good sign of a well-curated project.

**Comment by mgely** [comment]
> > I actually created requirements-dev.txt for this purpose.
> Is that in the repo somewhere?

It's in the development branch at the moment (I made it when i was implementing Black yesterday)

> > But we have to trust that a potential contributor will install black by calling
> > `pip install -r requirements-dev.txt`
> > and not run `pip-install black`.
> 
> That's true but working in a virtualenv for each project and using the project's `requirements-dev.txt` is pretty standard and can be written explicitly in just a couple lines of the readme.
> 
> I personally go for the simplest approach I can find that works on most platforms, and I try to stick to the norms of the Python community. Working in a virtualenv and using `requirements-dev.txt` is quite standard as far as I can tell. It's particularly useful to do this because you can set the buildbot to use the same virtualenv configuration. That way you only ever have to update packages and versions in one place.

I looked around, it does indeed seem to be pretty standard. Thank for your patience by the way!
I gone back to having a Black check in Travis in 75a29d8b781a3d8222356403a2c40c4709945729, and added the necessary information about the black version and requirements-dev.txt in the 
developer guide on the website.
