### ISSUE TITLE
circuits mode problem

### ISSUE THREAD

**Issue by gmxue** [qucat/qucat#75]
Write here a description of the bug. This could include: the code or steps to reproduce the bug, the behavior you would have expected and/or screenshots.
I build this circuits and calculate its mode
![image](https://user-images.githubusercontent.com/36075168/86192594-8b8f8900-bb7c-11ea-8a23-105385b2d3d5.png)
But when I change one of its Junction inductance , its mode change from 3 to 4
![image](https://user-images.githubusercontent.com/36075168/86192689-b843a080-bb7c-11ea-848a-9a090ee38078.png)
Is this a bug? or how can i analysis this problem?

**Comment by mgely** [comment]
Hi @gmxue 
This mode which appears (the first one) will probably not reflect the physical reality of the circuit..  It notably has an anharmonicity of 10^15 Hz and a frequency of 10^5 Herz!

To debug these problems, I would usually make use of the function which plots the current or voltage distribution for a certain mode (see https://qucat.org/tutorials/basics.html#Visualizing-a-normal-mode). However in this it didn't help me much.

So.. I know turn my attention to your choice of values for the circuit components and I see that many capacitances have the same values. This typically causes problems in QuCAT. 

This is not necessarily a bug. If you arrange identical capacitances in certain configurations (for example a balanced wheatstone bridge geometry https://en.wikipedia.org/wiki/Wheatstone_bridge), the equivelant capacitance of the circuit could be 0 or infinity. So theoretically your circuit could have a problem. If you build this circuit for example 
![image](https://user-images.githubusercontent.com/10977359/86221706-8aaf2500-bb85-11ea-9c31-82e70107dedb.png)
QuCAT will give an error, but it's not a bug, it's just that you have actually made something with an infinite eigen-frequency.

Keeping this in mind, I very slightly modified the values of your 100fF capacitances, so they are not identical (which actually corresponds to physical reality). And this solves the problem, there are only 3 modes again!
![image](https://user-images.githubusercontent.com/10977359/86221937-dbbf1900-bb85-11ea-99d3-66f18913aceb.png)

**Comment by gmxue** [comment]
Hi,Mario Gely
Thank you very much for you explaining. I will try to change my circuit model.
















At 2020-07-01 16:31:50, "Mario Gely" <notifications@github.com> wrote:

Hi @gmxue
This mode which appears (the first one) will probably not reflect the physical reality of the circuit.. It notably has an anharmonicity of 10^15 Hz and a frequency of 10^5 Herz!

To debug these problems, I would usually make use of the function which plots the current or voltage distribution for a certain mode (see https://qucat.org/tutorials/basics.html#Visualizing-a-normal-mode). However in this it didn't help me much.

So.. I know turn my attention to your choice of values for the circuit components and I see that many capacitances have the same values. This typically causes problems in QuCAT.

This is not necessarily a bug. If you arrange identical capacitances in certain configurations (for example a balanced wheatstone bridge geometry https://en.wikipedia.org/wiki/Wheatstone_bridge), the equivelant capacitance of the circuit could be 0 or infinity. So theoretically your circuit could have a problem. If you build this circuit for example

QuCAT will give an error, but it's not a bug, it's just that you have actually made something with an infinite eigen-frequency.

Keeping this in mind, I very slightly modified the values of your 100fF capacitances, so they are not identical (which actually corresponds to physical reality). And this solves the problem, there are only 3 modes again!
