### ISSUE TITLE
Link to google group for qucat forum is broken

### ISSUE THREAD

**Issue by AdriaanRol** [qucat/qucat#77]
When I click the link to the google group in the tutorial section of the documentation (see screenshot) I get redirected 

![image](https://user-images.githubusercontent.com/6142932/92086430-75938400-edca-11ea-8f2c-5bd65655b143.png)

I get redirected to a generic content unavailable page. This might have something to do with the access settings of the google group or the recent update to google groups. 

![image](https://user-images.githubusercontent.com/6142932/92086549-9c51ba80-edca-11ea-9c8d-af18e12b2473.png)

**Comment by mgely** [comment]
That's weird! works for me now..
To double check, this is the link: https://groups.google.com/forum/#!forum/qucat
Does it still bring you nowhere?

**Comment by mgely** [comment]
Just changed the settings such that the conversations are visible to everyone
![image](https://user-images.githubusercontent.com/10977359/92087523-e2f3e480-edcb-11ea-8432-8212055950e6.png)

**Comment by AdriaanRol** [comment]
yup, looks like that solved the problem 👍
