### ISSUE TITLE
opening GUI causes OS crash /  user logout on MacOS 10.14.6

### ISSUE THREAD

**Issue by gsteele13** [qucat/qucat#78]
What I did: 

`pip install qucat`

Created a notebook with following code

```
import numpy as np
import matplotlib.pyplot as plt
from qucat import Network,GUI,L,J,C,R

cir = GUI('basics.txt', # location of the circuit file
        edit=True, # open the GUI to edit the circuit
        plot=True, # plot the circuit after having edited it
        print_network=True # print the network
       )
```

The kernel hung for a while, then my screen went black, then I was presented with a MacOS login screen that is the same as when my computer reboots. My applications were all closed, so it seems I was logged out, but I did not see the bootup screen, so I guess it probably just killed my session and logged me out.

I will try again, but I will submit this issue just so I don't lose the text I've written if it crashes again.

**Comment by gsteele13** [comment]
Here are some of the error messages I see on my notebook console:

```
2020-10-09 09:55:24.704 python[47394:2716773] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated.}
2020-10-09 09:55:24.704 python[47394:2716773] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
2020-10-09 09:55:24.704 python[47394:2716773] XType: unable to make a connection to the font daemon!
2020-10-09 09:55:24.704 python[47394:2716773] registering /System/Library/Fonts/*, /System/Library/Fonts/Base/*, and /Library/Fonts/* locally
2020-10-09 09:55:37.660 python[47394:2716773] *** CFMessagePort: bootstrap_register(): failed 141 (0x8d) 'unknown error code', port = 0x2c03, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2020-10-09 09:55:37.814 python[47394:2716797] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection invalid
2020-10-09 09:55:42.803 python[47394:2716773] In -[NSApplication(NSQuietSafeQuit) _updateCanQuitQuietlyAndSafely], _LSSetApplicationInformationItem(NSCanQuitQuietlyAndSafely) returned error -600
```

Maybe I need to have the x-server installed and running?

**Comment by mgely** [comment]
Waht happened when you tried again? Did it log you out?

**Comment by gsteele13** [comment]
I've tried it again a few times. It never returns from the  `cir  = `  code cell, and I see the same  error messages ending  in  `NSQuietSafeQuit` in my terminal.

(The strange OS crash  /  logout thing didn't happen again yet...?)

**Comment by gsteele13** [comment]
I have since installed XQuartz, but that does not help. (Not sure if that is related to the issue?)

I'll try rebooting.

**Comment by gsteele13** [comment]
OK, things get stranger.

I rebooted and tried again. 

A program started to popup in my application tray at bottom of screen. The icon grew to about 20% of full size (icons are animated) and then screen went black. I briefly saw the white "mac" icon with a progress bar like on boot up but then very quickly got to the login screen and logged in again (my previous open programs all being closed). 

I'll try again now after this "flash" reboot and see what happens. 

Ironically, the only reason I wanted to run the GUI was to make a screen recording of how it works to make a project for a paid developer to code a gui circuit editor natively in the notebook in the web browser :)

**Comment by gsteele13** [comment]
Not sure where the problem is, but apparently python triggered 29875 macos system error log messages in 1 second when trying to open the gui...

```
Oct  9 13:48:04 TUD1001336 python[4623]: assertion failed: 18G6032: libxpc.dylib + 40562 [A1EABC2B-A88E-365C-AEA5-1543FD75BAC7]: 0x8d
Oct  9 13:48:10 --- last message repeated 29875 times ---
Oct  9 13:48:10 TUD1001336 python[4623]: libcoreservices: _dirhelper_userdir: 486: access: /var/folders/zz/zyxvpxvq6csfxvn_n2xcv138qb6r8t/: No such file or directory; attempting to recreate
Oct  9 13:48:10 TUD1001336 python[4623]: libcoreservices: _dirhelper_userdir: 529: bootstrap_look_up returned (ipc/send) invalid destination port
Oct  9 13:48:10 TUD1001336 python[4623]: assertion failed: 18G6032: libxpc.dylib + 40562 [A1EABC2B-A88E-365C-AEA5-1543FD75BAC7]: 0x8d
```

**Comment by mgely** [comment]
This is very strange, there have been problems on MAC OS before, but never like this..
It has worked fine on the two versions of the OS I tested it on.
Namely your old MAC :)

**Comment by gsteele13** [comment]
some googling:

https://www.steinberg.net/forums/viewtopic.php?t=104566

seems libxpc errors can cause hard reboots / crashes

seems libxpc is an implementation of IPC:

https://en.wikipedia.org/wiki/Inter-process_communication

My guess is that this is somehow related to Tk: I guess that python communicates to some Tk objects using the XPC library. 

It sounds /  looks like this occurs through a named pipe (/var/folders/....) and it seems the permission to create the file pipe is denied maybe, which leaves python no way to communicate to the expected Tk process...?

**Comment by gsteele13** [comment]
ok, some more googling:

https://www.python.org/download/mac/tcltk/

<img width="735" alt="Screenshot 2020-10-09 at 13 57 48" src="https://user-images.githubusercontent.com/16204006/95580323-7063cd80-0a37-11eb-8b91-2a7267ff55a0.png">

Maybe I need to install Tk separately?

**Comment by gsteele13** [comment]
maybe related:

https://github.com/ContinuumIO/anaconda-issues/issues/11165

**Comment by gsteele13** [comment]
Thinks now seem to work using the pip-installed version with the latest updates on MacOS, I'll close this isseu

**Comment by mgely** [comment]
Thanks for the update!! It's very difficult for me to debug these on my own, since I don't own a mac!
