### ISSUE TITLE
TypeError: '<' not supported between instances of 'ComplexElement' and 'int'

### ISSUE THREAD

**Issue by sudoyang** [qucat/qucat#79]
I followed the basic instruction but got the error in step 4.

[4]:

cir_prog = Network([
C(0,1,100e-15), # transmon
J(0,1,'Lj'),
C(0,2,100e-15), # resonator
L(0,2,10e-9),
C(1,2,1e-15), # coupling capacitor
C(2,3,0.5e-15), # ext. coupl. cap.
R(3,0,50)]) # 50 Ohm load

The instruction is here,
https://qucat.org/tutorials/basics.html

**Comment by mgely** [comment]
Hi! I just ran the following code
`from qucat import Network,C,J,L,R
cir_prog = Network([
C(0,1,100e-15), # transmon
J(0,1,'Lj'),
C(0,2,100e-15), # resonator
L(0,2,10e-9),
C(1,2,1e-15), # coupling capacitor
C(2,3,0.5e-15), # ext. coupl. cap.
R(3,0,50)]) # 50 Ohm load`
with the latest version of QuCAT, and got no errors.

Could you share the script that you are running (try and make it [as minimal as possible](https://en.wikipedia.org/wiki/Minimal_working_example)), as well as the [full error traceback](https://www.geeksforgeeks.org/python-traceback/)?

**Comment by sudoyang** [comment]
Hi mgely,

Thanks for the reply and sorry for the lacking of information. I just run the snippet above directly but still got error.

The qucat I have should be the newest one, since I tested below

➜  ~  pip install --upgrade qucat      
Requirement already satisfied: qucat in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (1.0.1)
Requirement already satisfied: scipy in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from qucat) (1.4.1)
Requirement already satisfied: pillow in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from qucat) (7.2.0)
Requirement already satisfied: matplotlib in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from qucat) (3.3.1)
Requirement already satisfied: sympy in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from qucat) (1.7.1)
Requirement already satisfied: numpy in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from qucat) (1.18.5)
Requirement already satisfied: cycler>=0.10 in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from matplotlib->qucat) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from matplotlib->qucat) (1.2.0)
Requirement already satisfied: certifi>=2020.06.20 in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from matplotlib->qucat) (2020.6.20)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from matplotlib->qucat) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from matplotlib->qucat) (2.8.1)
Requirement already satisfied: six in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from cycler>=0.10->matplotlib->qucat) (1.15.0)
Requirement already satisfied: mpmath>=0.19 in ./.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages (from sympy->qucat) (1.1.0)



 I have put the error message below. I run python via pyenv.

➜  ~ ipython
Python 3.6.6 (default, Aug 26 2019, 14:44:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from qucat import Network,C,J,L,R
   ...: cir_prog = Network([
   ...: C(0,1,100e-15), # transmon
   ...: J(0,1,'Lj'),
   ...: C(0,2,100e-15), # resonator
   ...: L(0,2,10e-9),
   ...: C(1,2,1e-15), # coupling capacitor
   ...: C(2,3,0.5e-15), # ext. coupl. cap.
   ...: R(3,0,50)]) # 50 Ohm load
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-8c63810b9f32> in <module>
      7 C(1,2,1e-15), # coupling capacitor
      8 C(2,3,0.5e-15), # ext. coupl. cap.
----> 9 R(3,0,50)]) # 50 Ohm load

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/qucat/core.py in __init__(self, netlist)
   1248 
   1249     def __init__(self, netlist):
-> 1250         super(Network, self).__init__(netlist)
   1251 
   1252 class GUI(Qcircuit):

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/qucat/core.py in __init__(self, netlist)
    161         # (the roots of which are the eigen-frequencies)
    162         self._char_poly_coeffs = [lambdify(self._no_value_components, c, 'numpy') 
--> 163             for c in self._network.compute_char_poly_coeffs(is_lossy = (len(self.resistors)>0))]
    164 
    165     @property

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/qucat/core.py in timed(*args, **kw)
     33     def timed(*args, **kw):
     34         ts = time.time()
---> 35         result = method(*args, **kw)
     36         te = time.time()
     37         if PROFILING:

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/qucat/core.py in compute_char_poly_coeffs(self, is_lossy)
   1626             char_poly = sp.collect(sp.expand(char_poly), w)
   1627             self.char_poly_order = sp.polys.polytools.degree(
-> 1628                 char_poly, gen=w)  # Order of the polynomial
   1629             # Get polynomial coefficients, index 0 = lowest order term
   1630             self.char_poly_coeffs_analytical =\

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/polytools.py in degree(f, gen)
   4464                 p, _ = poly_from_expr(f)
   4465             else:
-> 4466                 p, _ = poly_from_expr(f, gen)
   4467 
   4468     if isNum:

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/polytools.py in poly_from_expr(expr, *gens, **args)
   4271     """Construct a polynomial from an expression. """
   4272     opt = options.build_options(gens, args)
-> 4273     return _poly_from_expr(expr, opt)
   4274 
   4275 

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/polytools.py in _poly_from_expr(expr, opt)
   4301 
   4302     if domain is None:
-> 4303         opt.domain, coeffs = construct_domain(coeffs, opt=opt)
   4304     else:
   4305         coeffs = list(map(domain.from_sympy, coeffs))

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/constructor.py in construct_domain(obj, **args)
    284             result = None
    285         else:
--> 286             result = _construct_composite(coeffs, opt)
    287 
    288         if result is not None:

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/constructor.py in _construct_composite(coeffs, opt)
    241                 denom[monom] = ground.from_sympy(coeff)
    242 
--> 243             result.append(domain((numer, denom)))
    244 
    245     return domain, result

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/domains/domain.py in __call__(self, *args)
     82     def __call__(self, *args):
     83         """Construct an element of ``self`` domain from ``args``. """
---> 84         return self.new(*args)
     85 
     86     def normal(self, *args):

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/domains/fractionfield.py in new(self, element)
     36 
     37     def new(self, element):
---> 38         return self.field.field_new(element)
     39 
     40     @property

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/fields.py in field_new(self, element)
    215         elif isinstance(element, tuple) and len(element) == 2:
    216             numer, denom = list(map(self.ring.ring_new, element))
--> 217             return self.new(numer, denom)
    218         elif isinstance(element, str):
    219             raise NotImplementedError("parsing")

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/fields.py in new(self, numer, denom)
    164     def new(self, numer, denom=None):
    165         if denom is None: denom = self.ring.one
--> 166         numer, denom = numer.cancel(denom)
    167         return self.raw_new(numer, denom)
    168 

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/rings.py in cancel(self, g)
   2217             _, p, q = f.cofactors(g)
   2218 
-> 2219             if q.is_negative:
   2220                 p, q = -p, -q
   2221         else:

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/rings.py in is_negative(self)
    845     @property
    846     def is_negative(self):
--> 847         return self.ring.domain.is_negative(self.LC)
    848 
    849     @property

~/.pyenv/versions/3.6.6/envs/env366/lib/python3.6/site-packages/sympy/polys/domains/domain.py in is_negative(self, a)
    448     def is_negative(self, a):
    449         """Returns True if ``a`` is negative. """
--> 450         return a < 0
    451 
    452     def is_nonpositive(self, a):

TypeError: '<' not supported between instances of 'ComplexElement' and 'int'

**Comment by mgely** [comment]
I've managed to reproduce the problem by upgrading to sympy 1.7.1. (released Dec 12, 2020).
I'm working on resolving the problem, you can expect a new version of qucat adressing this within the next few hours.

**Comment by sudoyang** [comment]
Cool! Thanks for the efforts!

**Comment by mgely** [comment]
For the record, I have just set up automatic daily testing of the code, such that updates of dependencies don't break QuCAT without me knowing !

**Comment by mgely** [comment]
Try 
pip install qucat --upgrade
This should solve the problem

**Comment by mgely** [comment]
For the moment QuCAT will force the installation of sympy 1.6.1
As soon as the issue https://github.com/sympy/sympy/issues/20985 is resolved by sympy developpers, I can relax this requirement again.

**Comment by mgely** [comment]
The fix is corresponds to #80

**Comment by sudoyang** [comment]
works like a charm! Thanks for the fix.

**Comment by mgely** [comment]
The Sympy issue has been resolved, I am now relaxing the requirements on sympy to `sympy>=1.8`.
