### ISSUE TITLE
clarify error messages when trying to assign values to a fixed element, clarify gui about fixed elements

### ISSUE THREAD

**Issue by gsteele13** [qucat/qucat#83]
[Untitled.pdf](https://github.com/qucat/qucat/files/6370300/Untitled.pdf)

As a "newbie" user, I was a bit confused about giving values to labelled circuit elements. 

Apparently, this means that you can no longer assign values to them when calling eg. `eigenvalues()`, but this is not terribly obvious in GUI, and not super clear in intro docs (probably a good idea to point this out early on).

**Comment by gsteele13** [comment]
Also, if you run the same code twice, you get different error messages

**Comment by mgely** [comment]
Hi! Thanks for posting the issue, it's very helpful :)
Solved the bug in commit 43b88dad7bffc28216fd6e5a637cffe43e951a82, there will be  a new pip-installable version sometime tomorrow incorporating these changes!
